version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - CROUStillantNetwork

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - CROUStillantNetwork

networks:
  CROUStillantNetwork:
    external: true
