version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - CROUStillantNetwork

networks:
  CROUStillantNetwork:
    external: true
